### ISSUE TITLE
图片加载问题

### ISSUE THREAD

**Issue by sihuanhuan** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#102]
网页中部分图片加载错误
![image](https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/assets/98305651/b5a6bbed-50bc-43f6-8970-2aa0b261a8d6)
![image](https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/assets/98305651/ed03141e-8fd2-43a5-a95b-063d78dcb1f0)

**Comment by yuluo-yx** [comment]
感谢反馈，社区会尽快修复的

**Comment by yuluo-yx** [comment]
https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/pull/124
