### ISSUE TITLE
[Docs]: 译文有误

### ISSUE THREAD

**Issue by 397047243** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#108]
### Current State

**Description of the current issue**:
这两句话有冲突

**Link to the page, allows developers to better identify problems**:
https://sca.aliyun.com/en-us/docs/2022.0.0.0/user-guide/sentinel/overview/
**Screenshots (if relevant)**:
<img width="1322" alt="image" src="https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/assets/48161253/2ad066b3-6ae7-4982-831f-b69faa1aeb74">

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

None

**Comment by 397047243** [comment]
还有这两个地方
https://sca.aliyun.com/en-us/blog/IP-Protocal-Migration
![Snipaste_2023-12-13_13-30-52](https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/assets/48161253/6a276335-414b-4363-9f81-217a91ce7904)
![Snipaste_2023-12-13_13-34-32](https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/assets/48161253/807a659f-5ac1-4079-9309-bb1efc8af058)

**Comment by wtwtong** [comment]
I will do this

**Comment by yuluo-yx** [comment]
> I will do this

Good job! @wtwtong
