### ISSUE TITLE
官网很多图片都不显示了

### ISSUE THREAD

**Issue by koofio** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#109]
网址：https://sca.aliyun.com/zh-cn/

![image](https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/assets/6446430/a133168b-6d77-4ba5-92fd-229b92e3f96e)

**Comment by yuluo-yx** [comment]
https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/pull/124
