### ISSUE TITLE
Official Document Questions

### ISSUE THREAD

**Issue by cxhello** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#148]
https://sca.aliyun.com

https://spring-cloud-alibaba-group.github.io

Which documentation website of these two is correct?

**Comment by yuluo-yx** [comment]
Both are correct. Every so often, the first official website is updated with content

The first is public.
The second is github action deploy, not public.

**Comment by cxhello** [comment]
I know. thanks.
