### ISSUE TITLE
[Site]: 无法解析 org.springframework.ai:spring-ai-core:0.8.1

### ISSUE THREAD

**Issue by luckLs** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#155]
### Current State

**Description of the current state**:

**Link to the wensite page, allow developers to better understand the problem**:

**Screenshots (if relevant)**:

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

None

**Comment by yuluo-yx** [comment]
See: https://github.com/alibaba/spring-cloud-alibaba/issues/3712
