### ISSUE TITLE
关于文档【FAQ】的反馈

### ISSUE THREAD

**Issue by youyud** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#239]
[在此处输入反馈]
[基于网关实现 Spring Cloud 服务发现与路由](https://sca.aliyun.com/blog/SCA-Higress-Routing) 链接打不开

---
#### 文档详细信息

⚠ *请勿编辑此部分。sca.aliyun.com ➟ GitHub 问题链接必须具有此部分。*

* Version  ID: 2bac3769-2613-f739-4796-0737c7cd8919
* Content: [FAQ](https://sca.aliyun.com/docs/2023/overview/faq/)
* Content Source: https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/blob/develop-astro-sca/src/content/docs/2023/zh-cn/overview/faq.md
* Service: **用户指南/开发指南/运维指南**

**Comment by yuluo-yx** [comment]
Fixed
