### ISSUE TITLE
[Site]: https://sca.aliyun.com SpringAI 专栏链接失效

### ISSUE THREAD

**Issue by PolarishT** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#247]
### Current State

**Description of the current state**:
https://sca.aliyun.com SpringAI 专栏链接失效

**Link to the wensite page, allow developers to better understand the problem**:

**Screenshots (if relevant)**:
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/2d508b9a-9453-4ce0-8823-0f2acfdd7d81">

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

None

**Comment by yuluo-yx** [comment]
Thanks for your feedback, it has been fixed
