### ISSUE TITLE
关于文档【用户指南-配置中心-进阶指南】的反馈

### ISSUE THREAD

**Issue by Wizarder54088** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#294]
springc.config.import这里写错了，应该是spring.config.import吧。
![Uploading Snipaste_2024-10-23_09-48-22.png…]()

---
#### 文档详细信息

⚠ *请勿编辑此部分。sca.aliyun.com ➟ GitHub 问题链接必须具有此部分。*

* Version  ID: 2bac3769-2613-f739-4796-0737c7cd8919
* Content: [进阶指南](https://sca.aliyun.com/docs/2022/user-guide/nacos/advanced-guide/)
* Content Source: https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/blob/develop-astro-sca/src/content/docs/2022/zh-cn/user-guide/nacos/advanced-guide.md
* Service: **用户指南/开发指南/运维指南**

**Comment by yuluo-yx** [comment]
Can you create pr fix it?
