### ISSUE TITLE
官网待优化内容

### ISSUE THREAD

**Issue by steverao** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#45]
1. 左上角logo需要替换为最新的样式，最下方的愿景上的logo也是一样的。
2. 网站icon需要替换一下。
3. 文档中的图片背景需要调整为透明的。具体问题点是：用户指南->注册配置中心->概览中的内容。
4. http://fescar.io/zh-cn/docs/next/overview/roadmap#action，页面内容很乱，需要梳理调整一下，精简内容，重新排版。
5. 网站中的英文内容，有的是显示的中文，如果没有对应英文版本，要不就留空算了，http://fescar.io/en-us/blog

**Comment by yuluo-yx** [comment]
3，4，5 done!

**Comment by chickenlj** [comment]
6. 调整吊顶菜单

**Comment by yuluo-yx** [comment]
- 7. 中英文对照
- 8. http://fescar.io/zh-cn/versions 页面优化

**Comment by yuluo-yx** [comment]
> 6. 调整吊顶菜单

准备将开发者菜单空出来。不用建立新的顶部菜单了

**Comment by chickenlj** [comment]
> 

空出来的菜单位置，可以填充以下内容

微服务解决方案
免费版 https://free.aliyun.com/?searchKey=mse&spm=sca-website-free.topbar.0.0.0
企业版 https://www.aliyun.com/product/aliware/mse?spm=sca-website.topbar.0.0.0

**Comment by yuluo-yx** [comment]
6 7(需要前端同学处理) 8 10(内容未填充) done!

**Comment by yuluo-yx** [comment]
0728:

1. logo 太长
2. 微服务解决方案 -> 解决方案，通用性
3. 取消 RC1 和 RC2 的 tag 显示
4. 提供英文的 All Versions
5. 英文文档不要用 USer 大写和其他 tab 一致
6. 底部 Logo 太大了，调整尺寸
